name: Build Project
on:
  push:
  workflow_dispatch:
jobs:
  test-project:
    strategy:
      matrix:
        build_type: [Debug, Release]
        # compiler: [gcc, clang]
    name: Dalotia Evaluation Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0
    # https://github.com/actions/checkout/issues/462#issuecomment-1697584038
    - name: Configure CMake
        env:
          GH_PAT: ${{ READ_TOKEN }}
        run: |
          # Need a little regex here so we can download repo with PAT
          sed -i 's|git@github.com:|https://$ENV\{GH_PAT\}@github.com/|g' CMakeLists.txt
          cmake -S . -B build
    - name: Configure and Build Project
      uses: threeal/cmake-action@v1.3.0
      with:
        run-build: true
        build-args: --config ${{ matrix.build_type }}
        # cxx-compiler: ${{ matrix.compiler }}
        build-dir: build-${{ matrix.build_type }}
